### ISSUE TITLE
[Bug] Papi 插件重载时拓展不会重新注册导致变量失效

### ISSUE THREAD

**Issue by Yurinann** [xming-cn/SbPlaceholder-Wiki#2]
如题，这是一个比较常见的问题，解决方法也很简单：在注册的拓展类里加入以下代码即可。

```
    @Override
    public boolean persist() {
        return true; // This is required or else PlaceholderAPI will unregister the Expansion on reload
    }
```

相关链接：https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/PlaceholderExpansion#full-example-2

**Comment by xming-cn** [comment]
你的进度真的很快，马上就要结束了，祝你好运bWdlYWVlXzE1X2ZzdGlhaG4=HEX5845 is big

**Comment by xming-cn** [comment]
这个问题会随着下个版本一起被修复
